server:
  port: 8084  # Change this if needed

spring:
  application:
    name: api-gateway  # Ensure this matches what you want in Eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables automatic route discovery via Eureka
          lower-case-service-id: true  # Helps match service names correctly
      routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
            - Path=/users/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
            - Path=/hotels/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
            - Path=/ratings/**
         

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Ensure Eureka server URL is correct
    register-with-eureka: true  # Ensure service is registered
    fetch-registry: true  # Ensure registry is fetched from Eureka
  instance:
    hostname: localhost
