server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitu2016/Microservices-Configuration-Server.git
          clone-on-start: true